apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf-cm
data:
  # we use the pipe to glue the value written in many rows to the specific key (nginx.conf)
  nginx.conf: |
    server {
        listen  80;
        server_name localhost;
        location / {
            root /usr/share/nginx/html;
            index index.html  index.htm;
        }
        #redirect server error pages to the static page /50x.html
        #
        error_page  500 502 503 504 /50x.html;
        location = /50x.html {
            root /usr/share/nginx/html
        }
        location /health {
            aceces_log off;
            return 200 "healthy\n";
        }
    }
